spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB 
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    dynamic:
      primary: master # 设置主数据源名称
      strict: false # 严格匹配数据源，默认false. true未匹配到指定数据源时抛异常，false使用默认数据源
      datasource:
        master: # 主数据源
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/home?useUnicode=true&characterEncoding=utf8
          username: root
          password: qsyy


mybatis-plus:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
# 文件上传配置

logging:
  config: classpath:log4j2/log4j2.xml
#######配置#######
swagger:
  enable: true
download:
  request-path: out/request/